source 'http://rubygems.org'
gem 'rack'
gem 'rack-protection'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'mongoid'
gem 'bson'
gem 'bson_ext'
gem 'selenium', :require => 'selenium/server'
gem 'selenium-webdriver'
gem 'resque', :require => 'resque/server'
gem 'logger'
gem 'foreman'
gem 'thin'
gem 'shotgun'

gem 'pry-padrino'
